### ISSUE TITLE
小白学习请教

### ISSUE THREAD

**Issue by mumu0419** [Uni-Gal/GalCharacterConnector#4]
您好，非常感谢您分享的开源项目。
因为想做一个基于知识图谱的web小软件，找到了您的这个项目，但是我只是python入门水平，不知道怎么使用这个框架，希望您可以不吝指点一下，我看您文档里的技术栈，那些都还不太了解，怎样快速学习，上手用上这个框架呢?
ps:参观了您的图虫主页，摄影也这么好！

**Comment by hokaso** [comment]
抱歉小伙伴……刚刚才看到你的评论……直接按readme启动就行，可以先去大致了解一下Springboot和vue.js，b站上有很多教程，如果基础ok的话直接看他们官网的文档也可以入门~ 如果你想拿这个做别的用途，直接改mybatis即可~ 其实如果不想深入学习java的话，用py重构一个后端，实现框架中那9个关键接口就行；其实这个项目最难的地方还是前端，各种交互和点击事件，设计起来比较繁琐。
